package com.cinebook;
import jakarta.persistence.*; import jakarta.validation.constraints.*; import org.springframework.boot.*; import org.springframework.boot.autoconfigure.*; import org.springframework.context.annotation.Bean; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.beans.factory.annotation.Value; import java.time.*; import java.util.*; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets;
@SpringBootApplication public class App{
 public static void main(String[]x){SpringApplication.run(App.class,x);}
 @Bean CommandLineRunner seed(MovieRepo m,UserRepo u){return x->{if(m.count()==0){String[]a={"RRR","Baahubali: The Beginning","Baahubali 2: The Conclusion","Pushpa: The Rise","Pushpa 2: The Rule","Kalki 2898 AD","Devara","Salaar","Hanuman","Jersey","Arjun Reddy","Mahanati","Sita Ramam","Rangasthalam","Ala Vaikunthapurramuloo","Eega","Magadheera","Pokiri","Athadu","Bommarillu","Happy Days","Manam","Ye Maaya Chesave","Fidaa","Geetha Govindam","Agent Sai Srinivasa Athreya","Brochevarevarura","Jathi Ratnalu","DJ Tillu","Tillu Square","Hi Nanna","Dasara","Virupaksha","Kantara","Kushi","Love Story","Shyam Singha Roy","Vakeel Saab","Bheemla Nayak","Saripodhaa Sanivaaram","Guntur Kaaram","Family Star","Eagle","Saindhav","Miss Shetty Mr Polishetty","Balagam","Baby","MAD","Ambajipeta Marriage Band","Gaami","Gangs of Godavari","Mathu Vadalara 2","Lucky Baskhar","Mechanic Rocky","Robinhood","Thandel","Court","HIT: The First Case","HIT: The Second Case","Goodachari","Kshanam","Evaru","Awe","C/o Kancharapalem","Pelli Choopulu","RX 100","Uppena","Color Photo","Middle Class Melodies","Raja Raja Chora","Cinema Bandi","Major","Ante Sundaraniki","Sammohanam","Dear Comrade","World Famous Lover","Taxiwala","MCA","Ninnu Kori","Nani's Gang Leader","Leader","Vedam","Prasthanam","Gamyam","Godavari","Anand","Arya","Arya 2","Julayi","Race Gurram","Attarintiki Daredi","Gabbar Singh","Temper","Janatha Garage","Nannaku Prematho","Orange","Oopiri","Kshanam 2","Bheeshma","Jaanu","Vakeel Saab 2"};for(int i=0;i<100;i++)m.save(new Movie(a[i],120+i%45,4.1+(i%9)/10d));}if(u.count()==0)u.save(new User("demo@cinebook.local","Demo@123","Demo User","9999999999"));};}
}
@Entity class Movie{@Id @GeneratedValue Long id;String title="",language="Telugu",certificate="UA",poster="https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80";int duration;double rating;Movie(){}Movie(String t,int d,double r){title=t;duration=d;rating=r;}}
@Entity @Table(name="app_user")class User{@Id @GeneratedValue Long id;@Column(unique=true)String email;String password,name,phone;User(){}User(String e,String p,String n,String ph){email=e;password=p;name=n;phone=ph;}}
@Entity class Booking{@Id @GeneratedValue Long id;Long userId,movieId;String showTime,seats,status,paymentId;double amount;Instant createdAt=Instant.now();Booking(){}Booking(Long u,Long m,String s,String se,double a,String p){userId=u;movieId=m;showTime=s;seats=se;amount=a;paymentId=p;status="CONFIRMED";}}
interface MovieRepo extends org.springframework.data.jpa.repository.JpaRepository<Movie,Long>{}interface UserRepo extends org.springframework.data.jpa.repository.JpaRepository<User,Long>{Optional<User>findByEmail(String e);}interface BookingRepo extends org.springframework.data.jpa.repository.JpaRepository<Booking,Long>{}
record Login(String email,String password){}record Register(String email,String password,String name,String phone){}record Checkout(Long userId,Long movieId,String showTime,String seats,@Positive double amount,String paymentReference){}
@org.springframework.stereotype.Service class SmsService{@Value("${app.sms-enabled:false}")boolean enabled;@Value("${TWILIO_ACCOUNT_SID:}")String sid;@Value("${TWILIO_AUTH_TOKEN:}")String token;@Value("${app.twilio-from:}")String from;void send(String to,String body){if(!enabled){System.out.println("SMS disabled; would send: "+body);return;}try{String form="To="+URLEncoder.encode(to,StandardCharsets.UTF_8)+"&From="+URLEncoder.encode(from,StandardCharsets.UTF_8)+"&Body="+URLEncoder.encode(body,StandardCharsets.UTF_8);HttpRequest r=HttpRequest.newBuilder(URI.create("https://api.twilio.com/2010-04-01/Accounts/"+sid+"/Messages.json")).header("Authorization","Basic "+Base64.getEncoder().encodeToString((sid+":"+token).getBytes())).header("Content-Type","application/x-www-form-urlencoded").POST(HttpRequest.BodyPublishers.ofString(form)).build();HttpClient.newHttpClient().send(r,HttpResponse.BodyHandlers.discarding());}catch(Exception e){System.err.println("SMS send failed: "+e.getMessage());}}}
@RestController @RequestMapping("/api") @CrossOrigin class Api{final MovieRepo m;final UserRepo u;final BookingRepo b;final SmsService sms;Api(MovieRepo m,UserRepo u,BookingRepo b,SmsService s){this.m=m;this.u=u;this.b=b;this.sms=s;}@GetMapping("/health")Map<String,String>health(){return Map.of("status","UP");}@GetMapping("/movies")List<Movie>movies(){return m.findAll();}@PostMapping("/auth/login")ResponseEntity<?>login(@RequestBody Login x){return u.findByEmail(x.email()).filter(v->v.password.equals(x.password())).<ResponseEntity<?>>map(v->ResponseEntity.ok(Map.of("token",UUID.randomUUID().toString(),"userId",v.id,"name",v.name))).orElse(ResponseEntity.status(401).body(Map.of("message","Invalid email or password")));}@PostMapping("/auth/register")ResponseEntity<?>register(@RequestBody Register x){if(u.findByEmail(x.email()).isPresent())return ResponseEntity.badRequest().body(Map.of("message","Email already registered"));User v=u.save(new User(x.email(),x.password(),x.name(),x.phone()));return ResponseEntity.status(201).body(Map.of("userId",v.id));}@PostMapping("/bookings")ResponseEntity<?>book(@RequestBody Checkout x){if(!u.existsById(x.userId())||!m.existsById(x.movieId()))return ResponseEntity.badRequest().body(Map.of("message","Invalid booking"));Booking z=b.save(new Booking(x.userId(),x.movieId(),x.showTime(),x.seats(),x.amount(),x.paymentReference()));User v=u.findById(x.userId()).orElseThrow();sms.send(v.phone,"CineBook: booking "+z.id+" confirmed. Payment "+z.paymentId);return ResponseEntity.status(201).body(Map.of("bookingId",z.id,"status",z.status,"paymentId",z.paymentId));}}
