apiVersion: v1
kind: Secret
metadata: {name: cinebook-secrets, namespace: cinebook}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://RDS_ENDPOINT:5432/cinebook
  SPRING_DATASOURCE_USERNAME: cinebook
  SPRING_DATASOURCE_PASSWORD: REPLACE_ME
  JWT_SECRET: REPLACE_WITH_32_CHAR_SECRET
  SMS_ENABLED: "false"
  TWILIO_ACCOUNT_SID: ""
  TWILIO_AUTH_TOKEN: ""
  TWILIO_FROM: ""
